# This file contains a formal specification for the fingering of the
# Yamaha WX-7 electronic wind instrument, based on the original
# manual and experimentation

# It is a permissive fingering: all fingerings result in a note

[metadata]
author = 'Tom Ritchford (tom@swirly.com)'
version = 'v0.1.0'
name = 'Fingering system for the Yamaha WX7 electronic wind instrument'
tags = ['WX7', 'Yamaha', 'WX', 'YamahaWX']
language = 'en'

# left:

[buttons.'B key']
short_name = 'L1'
press = 'left-1'

[buttons.'A# key']
short_name = 'L2b'
press = 'left-2'
# Just for that one purpose

[buttons.'A key']
short_name = 'L2'
press = 'left-2'

[buttons.'G key']
short_name = 'L3'
press = 'left-3'

# NOTE: also takes F-G#, F#-G#, aside from the lift
[buttons.'G# key']
short_name = 'L4a'
press = 'left-4'
# Modifier +1 but only for C1, G1, A1, B1, C2, C#2

[buttons.'Low B key']
short_name = 'L4b'
press = 'left-4'
# G -> G#
# D# -> Bb
# D -> B
# C -> B


#
# Right hand
#

[buttons.'Whole tone up key']
short_name = 'R1b'
press = 'right-1'
modifer = +2

[buttons.'Semitone tone up key']
short_name = 'R2b'
press = 'right-2'
modifier = +1

[buttons.'F key']
short_name = 'R1'
press = 'right-1'

[buttons.'E key']
short_name = 'R2'
press = 'right-2'

[buttons.'F# key']
short_name = 'R3b'
press = 'right-3'
modifier = +1

[buttons.'D key']
short_name = 'R3'
press = 'right-3'
# Note: also used for F# SPECIAL

[buttons.'D# key']
short_name = 'R4b'
press = 'right-4'
modifier = -1

[buttons.'C key']
short_name = 'R4'
press = 'right-4'
modifier = -2
# Does not work with R4b! :-D SPECIAL

[buttons.'Octave +3']
short_name = '+3'
press = 'left-thumb'
octave = +3

[buttons.'Octave +2']
short_name = '+2'
press = 'left-thumb'
octave = +2

[buttons.'Octave +1']
short_name = '+1'
press = 'left-thumb'
octave = +1

[buttons.'Octave -1']
short_name = '-1'
press = 'left-thumb'
octave = -1

[buttons.'Octave -2']
short_name = '-2'
press = 'left-thumb'
octave = -2

[octaves]
# What happens if two octave buttons on the same side are pressed?
overlap = 'biggest'

# What happens if two octave buttons, one plus, one minus, are pressed?
priority = 'plus'

# A lift is a fingering that is missing some fingers

[[lifts]]
# If any two of these buttons are up, in a position where they were all down
# then go up by an octave - except for Bb it goes to B, 13 semitones. :-D
buttons = 'L1 L2 L3'
count = 2
modifier = +12
special = {'Bb0': +13}

[fingerings]

C_1 = 'L1  L2  L3      R1  R2  R3  R4  '
Db1 = 'L1  L2  L3      R1  R2  R3  R4  '
D_1 = 'L1  L2  L3      R1  R2  R3      '
E_1 = 'L1  L2  L3      R1  R2          '
F_1 = 'L1  L2  L3      R1              '
Gb1 = 'L1  L2  L3          R2          '
G_1 = 'L1  L2  L3                      '
A_1 = 'L1  L2                          '
Bb1 = 'L1  L2b                         '
B_1 = 'L1                              '
C_2 = '    L2                          '
Db1 = '                                '
