[layout]
title = '''
<svg>
  <text font-size="60px" font-family="monospace" text-anchor="middle" x="1000" y="100">
        Fingering chart for the Baroque family of recorders
  </text>
  <text font-size="30px" font-family="monospace" text-anchor="middle" x="1000" y="170">
      Copyleft <tspan fill="transparent">©</tspan> 2026, Tom Ritchford. No rights reserved.
  </text>
  <use href="#copyleft" x="232" y="48" transform="scale(3, 3)" />
</svg>
'''

[layout.styles]
outline = {fill = 'white', stroke = 'black', stroke-width = 1.5}
caption = {fill = 'black', font-size = "40px", font-family = 'monospace', text-anchor = 'middle'}

[layout.defs]
pad = '<circle cx="50" cy="50" r="50" />'
little-hole = '<circle cx="80" cy="55" r="20" />'
big-hole = '<circle cx="30" cy="30" r="30" />'

horizontal-line = '<rect x="0" y="50" width="120" height="1" style="fill: black;"/>'
octave = '<path d="  M 0,50   A 50,50 0 0 0 100,50   Z  " fill="black" />'

[layout.pieces.left-thumb.parts]
_off = 'pad @ outline'
oct = 'pad @ outline + octave'
left-thumb = 'pad'

[layout.pieces._separator-1.parts]
_off = 'horizontal-line'

[layout.pieces.left-1.parts]
_off = 'pad @ outline'
left-1 = 'pad'

[layout.pieces.left-2.parts]
_off = 'pad @ outline'
left-2 = 'pad'

[layout.pieces.left-3.parts]
_off = 'pad @ outline'
left-3 = 'pad'

[layout.pieces._separator-2.parts]
_off = 'horizontal-line'

[layout.pieces.right-1.parts]
_off = 'pad @ outline'
right-1 = 'pad'

[layout.pieces.right-2.parts]
_off = 'pad @ outline'
right-2 = 'pad'

[layout.pieces.right-3.parts]
_off = 'little-hole @ outline + big-hole @ outline'
right-3 = 'little-hole + big-hole'
right-3-half = 'little-hole @ outline + big-hole'

[layout.pieces.right-4.parts]
_off = 'little-hole @ outline + big-hole @ outline'
right-4 = 'little-hole + big-hole'
right-4-half = 'little-hole @ outline + big-hole'
