# This file contains a formal specification for the Baroque or English fingering
# of the recorder family, using a system called `fing` designed to represent
# any fingering for any wind instrument or similar device.
#
# It's written in a format called TOML designed to be straight-forward for both humans
# and computers to read and write.
#
# Comments are line like this one that start with a # and are just used to communicate
# with the reader - they are ignored by computers.
#


[metadata]
author = 'Tom Ritchford (tom@swirly.com)'
version = 'v0.1.0'
name = 'Baroque fingering system for the recorder'
tags = ['recorder', 'baroque']
language = 'en'

# A **key** is an affordance like a key, pad, hole, button, or lever
# that controls a wind instrument.
#
# A key has three parts:
#
#  * "short name": usually 2 or 3 characters, for text-based fingering charts
#
#  * "press": the finger or other thing that presses or actuates this key
#
#  * "description": an optional field with more text information for the player
#
# Multiple keys might share the same physical location.

# For example, the thumb hole on the recorder can be covered in two different ways:
#
# * fullly to produce the lower octave
# * half-covered for the upper octave
#
# This is represented by having two different keys: "left-thumb" and "octave".

#
#            ******* Left hand *******
#

[keys.left-thumb]
short_name = 'lt'
press = "left-thumb"

[keys.octave]
short_name = 'oct'
press = "left-thumb"
description = 'Half-cover the thumb hole with the nail'

[keys.left-1]
short_name = 'l1'
press = "left-1"

[keys.left-2]
short_name = 'l2'
press = "left-2"

[keys.left-3]
short_name = 'l3'
press = "left-3"

#
#            ******* Right hand *******
#

[keys.right-1]
short_name = 'r1'
press = "right-1"

[keys.right-2]
short_name = 'r2'
press = "right-2"

[keys.right-3]
short_name = 'r3'
press = "right-3"

[keys.right-3-half]
short_name = 'r3h'
press = "right-3"
description = 'Slide the right ring finger back to only close the large hole'

[keys.right-4]
short_name = 'r4'
press = "right-4"

[keys.right-4-half]
short_name = 'r4h'
press = "right-4"
description = 'Slide the right little finger back to only close the large hole'

[keys.cover-bell]
short_name = 'cb'
press = 'knee'
description = 'Partly cover the bell of the instrument with the knee'

# Here's where the real action is: the fingering chart.
#
# Fingering charts always start with a special value `all` which
# lists all of the keys used in the chart in order.
#
# Indentation, whitespace, and the `_` in note names like `C_1` are ignored
# and in fact you can enter the keys in any order if you like.

[fingerings]
all = 'oct lt l1 l2 l3 r1 r2 r3 r3h r4 r4h cb  '

C_1 = 'lt  l1  l2  l3  r1  r2  r3  r4      '
Db1 = 'lt  l1  l2  l3  r1  r2  r3  r4h     '
D_1 = 'lt  l1  l2  l3  r1  r2  r3          '
Eb1 = 'lt  l1  l2  l3  r1  r2  r3h         '
E_1 = 'lt  l1  l2  l3  r1  r2              '
F_1 = 'lt  l1  l2  l3  r1      r3  r4      '
Gb1 = 'lt  l1  l2  l3      r2  r3          '
G_1 = 'lt  l1  l2  l3                      '
Ab1 = 'lt  l1  l2      r1  r2  r3h         '
A_1 = 'lt  l1  l2                          '
Bb1 = 'lt  l1  l2      r1                  '
B_1 = 'lt  l1                              '
C_2 = 'lt      l2                          '
Db2 = '    l1  l2                          '
D_2 = '        l2                          '
Eb2 = '        l2  l3  r1  r2  r3          '
E_2 = 'oct l1  l2  l3  r1  r2              '
F_2 = 'oct l1  l2  l3  r1      r3          '
Gb2 = 'oct l1  l2  l3      r2              '
G_2 = 'oct l1  l2  l3                      '
Ab2 = 'oct l1  l2      r1                  '
A_2 = 'oct l1  l2                          '
Bb2 = 'oct l1  l2          r2  r3  r4h     '
B_2 = 'oct l1  l2      r1  r2              '
C_3 = 'oct l1          r1  r2              '
Db3 = 'oct l1      l3  r1      r3      cb  '
D_3 = 'oct l1      l3  r1      r3          '

# The lowest_c section is where we assign the actual octave ranges
# to the specific instruments in the family.
#
# The `lowest_c` for an instrument is the pitch of the lowest C
# within its tuning.

[lowest_c]

# From https://www.rochars.org/recorder-freqency-ranges
contrabass = 'F2'
great-bass = 'C3'
bass = 'F3'
tenor = 'C4'
alto = 'F4'
soprano = 'C5'
sopranino = 'F5'
garklein = 'C6'

# TO MOVE elsewhere
# Wind instruments are played by blowing and fingering. Players control the pictch of
# their instrument using fingering, breath, embouchure and perhaps other actions like
# covering the bell.
